spring.application.name=enajenarte

# Perfil activo por defecto para trabajar en local
spring.profiles.active=dev

# Configuracion de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect