# Production environment
# API and MariaDB will run inside Docker Compose

server.port=8085

spring.datasource.url=jdbc:mariadb://db:3306/${MARIADB_DATABASE}
spring.datasource.username=${MARIADB_USER}
spring.datasource.password=${MARIADB_PASSWORD}